name: CI/CD for react-app

on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependecnies
        run: npm install

      - name: Making build
        run: npm run build

      - name: Copy Build to Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ec2-13-48-84-43.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          scp -i ssh_key -o StrictHostKeyChecking=no -r ./dist/* ${{secrets.USER}}@${{secrets.SERVER_IP}}:/var/www/react-app/

      - name: Restart Nginx Service
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{secrets.USER}}@${{secrets.SERVER_IP}} << 'EOF'
          sudo systemctl restart nginx
          EOF

      - name: Removing ssh key
        run: rm -rf home/runner/.ssh/*
