name: CI/CD for react-app

on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependecnies
        run: npm install

      - name: Making build
        run: npm run build

      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} # My SSH private key
          known_hosts: ${{ secrets.SERVER_IP }} # My hostname of your server
          
      - name: Copy build to server
        run: |
          scp -i /home/runner/.ssh/id_rsa StrictHostKeyChecking=no -r ./dist/* ${{secrets.USER}}@${{secrets.SERVER_IP}}:/var/www/react-app/

      - name: Restart Nginx Service
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.SERVER_IP}} << 'EOF'
          sudo systemctl restart nginx
          EOF

      - name: Removing ssh key
        run: rm -rf /home/runner/.ssh/*
