name: CI/CD for react-app

on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependecnies
        run: npm install

      - name: Making build
        run: npm run build

      - name: SSH Setup
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{secrets.KNOWN_HOST}} >> ~/.ssh/known_hosts

      - name: Copy Build to Server
        run: scp -i ssh_key -o StrictHostKeyChecking=no -r ./dist ${{secrets.USER}}@${{secrets.SERVER_IP}}:/home/ec2-user

      - name: Moving build to get served by Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{secrets.USER}}@${{secrets.SERVER_IP}} << 'EOF'
          sudo cp -r dist/* /var/www/react-app/ 
          sudo systemctl restart nginx
          EOF

      - name: Removing ssh key
        run: rm -rf home/runner/.ssh/*
